### ISSUE TITLE
TypeError: DynamicCrowdAvoider.__init__() got an unexpected keyword argument 'environment'

### ISSUE THREAD

**Issue by xzhuzhu** [hubernikus/dynamic_obstacle_avoidance#10]
Hi， thanks for your great work.
When I run the code animation_multiple_agent.py from the dynamic_obstacle_avoidance/examples/multi_agent_scenarios/, I met the error as: TypeError: DynamicCrowdAvoider.__init__() got an unexpected keyword argument 'environment'. How to fix this, thanks.

**Comment by hubernikus** [comment]
Hello.
The file was an old example, that was not working anymore. 

You could try build on the example for multiple obstacles (including one moving one):
https://github.com/hubernikus/dynamic_obstacle_avoidance/blob/main/examples/animation_moving_obstacle.py
