### ISSUE TITLE
Cannot find Pose and Twist from vartools

### ISSUE THREAD

**Issue by Woodenonez** [hubernikus/dynamic_obstacle_avoidance#12]
Hi Lukas,

While trying with your code, I met the following error:
```
Traceback (most recent call last):
  File ".../dynamic_obstacle_avoidance/examples/vectorfield_inverse_obstacle.py", line 14, in <module>
    from dynamic_obstacle_avoidance.obstacles import Polygon, Cuboid, Ellipse
  File ".../dynamic_obstacle_avoidance/dynamic_obstacle_avoidance/obstacles/__init__.py", line 5, in <module>
    from ._base import Obstacle, GammaType
  File ".../dynamic_obstacle_avoidance/dynamic_obstacle_avoidance/obstacles/_base.py", line 29, in <module>
    from vartools.states import Pose, Twist
ImportError: cannot import name 'Pose' from 'vartools.states' (.../dynamic_obstacle_avoidance/libraries/various_tools/vartools/states.py)
```
I checked vartools.states and found:
![image](https://github.com/user-attachments/assets/02f7529b-b088-4f89-89cf-0f03d236650b)
So there are actually no Pose and Twist classes. I tried to use ObjectPose and ObjectTwist but got more errors. I'm guessing they are updated only locally. Could you please fix this?

Thank you!

**Comment by hubernikus** [comment]
I can not replicate your error. In the latest verison of vartools.states, there is Pose & Twist:
https://github.com/hubernikus/various_tools/blob/main/vartools/states.py

**Comment by Woodenonez** [comment]
Ah I see. In this repo, your submodule is an old version. I'll clone the newest version then. Thanks!
